#!/usr/bin/env python3
"""Build the master comparison matrices for Part IV §21 of the AI model documentation suite.

Reads all providers/*.models.json sidecars and prints four GitHub-flavored markdown
tables to stdout:
  1. Frontier tier            (tier == "frontier")
  2. Mid / budget tier        (tier in {"mid", "small"})
  3. Embeddings               (tier == "embedding")
  4. Local-capable            (local_capable == true, any tier)

Rules (00_CONVENTIONS.md): null prices render as `n/p` (not published), never 0;
0.0 is rendered as 0.00 only where the sidecar explicitly says the model is free.
No numbers are invented — every cell comes straight from the sidecar JSON.

Usage:  python3 scripts/build_matrix.py            # tables to stdout
        python3 scripts/build_matrix.py --check    # row-count summary only
"""
import json
import sys
from pathlib import Path

PROVIDERS_DIR = Path(__file__).resolve().parent.parent / "providers"

# filename stem -> short display name (stable across sidecar "provider" field wording)
SHORT = {
    "openai": "OpenAI",
    "gemini": "Gemini",
    "anthropic": "Anthropic",
    "bedrock": "Bedrock",
    "azure": "Azure",
    "openrouter": "OpenRouter",
    "ollama": "Ollama",
    "huggingface": "HF",
}
ORDER = ["openai", "gemini", "anthropic", "bedrock", "azure", "openrouter", "ollama", "huggingface"]

MOD_ABBR = {"text": "T", "image": "I", "audio": "A", "video": "V", "pdf": "P",
            "document": "P", "embedding": "E", "music": "M"}


def fmt_tokens(n):
    if n is None:
        return "n/p"
    if n >= 1_000_000:
        s = f"{n / 1_000_000:.2f}".rstrip("0").rstrip(".")
        return f"{s}M"
    if n >= 1_000:
        s = f"{n / 1_000:.1f}".rstrip("0").rstrip(".")
        return f"{s}k"
    return str(n)


def fmt_price(p):
    if p is None:
        return "n/p"
    if p == 0:
        return "0.00"
    return f"{p:g}"


def fmt_mods(m):
    ins = "".join(MOD_ABBR.get(x, x[:1].upper()) for x in (m.get("modalities_in") or []))
    outs = "".join(MOD_ABBR.get(x, x[:1].upper()) for x in (m.get("modalities_out") or []))
    if not ins and not outs:
        return "n/p"
    return f"{ins or '?'}->{outs or '?'}"


def fmt_bool(b):
    return {True: "Y", False: "N"}.get(b, "n/p")


def load():
    rows = []
    for stem in ORDER:
        f = PROVIDERS_DIR / f"{stem}.models.json"
        data = json.loads(f.read_text())
        for m in data["models"]:
            m["_prov"] = SHORT[stem]
            m["_prov_ord"] = ORDER.index(stem)
            rows.append(m)
    return rows


def sort_key(m):
    # provider order, then price_in ascending with unpublished last, then id
    p = m.get("price_in_per_1m")
    return (m["_prov_ord"], p is None, p if p is not None else 0, m["id"])


HEADER = ("| Model id | Provider | Context | Max out | Modalities | Tools | $in/1M | $out/1M | Conf |\n"
          "|---|---|---|---|---|---|---|---|---|")


def emit(title, rows, extra_note=""):
    print(f"### {title} ({len(rows)} rows)\n")
    print(HEADER)
    for m in sorted(rows, key=sort_key):
        print("| `{}` | {} | {} | {} | {} | {} | {} | {} | {} |".format(
            m["id"], m["_prov"], fmt_tokens(m.get("context_tokens")),
            fmt_tokens(m.get("max_output_tokens")), fmt_mods(m),
            fmt_bool(m.get("tool_use")), fmt_price(m.get("price_in_per_1m")),
            fmt_price(m.get("price_out_per_1m")), m.get("confidence", "n/p")))
    if extra_note:
        print(f"\n{extra_note}")
    print()


def main():
    rows = load()
    frontier = [m for m in rows if m["tier"] == "frontier"]
    midbudget = [m for m in rows if m["tier"] in ("mid", "small")]
    embeddings = [m for m in rows if m["tier"] == "embedding"]
    local = [m for m in rows if m.get("local_capable")]

    if "--check" in sys.argv:
        print(f"total={len(rows)} frontier={len(frontier)} mid/budget={len(midbudget)} "
              f"embeddings={len(embeddings)} local={len(local)}")
        return

    print(f"<!-- generated by scripts/build_matrix.py from {len(rows)} sidecar rows; "
          "do not hand-edit tables -->\n")
    emit("Frontier tier", frontier,
         "Note: OpenRouter/Bedrock/Azure rows duplicate lab models by design (same model, "
         "different platform terms/prices); price divergence between rows for the same model "
         "is real observed listing data, not an error — see section 23.")
    emit("Mid / budget tier", midbudget,
         "Note: `0.00` rows are explicitly free listings (OpenRouter `:free` variants, "
         "moderation endpoint); `n/p` means the sidecar records no published per-token price "
         "(open-weight or compute-billed models).")
    emit("Embedding models", embeddings,
         "Note: embedding output price is `n/p` by nature (input-only billing) for most rows.")
    emit("Local-capable models (any tier)", local,
         "Note: rows overlap with the tier tables above; this view filters "
         "`local_capable: true`. Prices shown are hosted-endpoint prices where a hosted "
         "listing exists; local runs are compute-cost-only.")


if __name__ == "__main__":
    main()
