import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the GENERATED plane (plugin instance "generated", route /views).
const sidebars: SidebarsConfig = {
  generated: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
