#!/usr/bin/env python3
"""Seed deterministic derived views and datasets with exact sha256 provenance hashes."""

import hashlib
import json
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

def sha256_of(rel_path: str) -> str:
    p = ROOT / rel_path
    if not p.is_file():
        raise FileNotFoundError(f"Missing file: {p}")
    return "sha256:" + hashlib.sha256(p.read_bytes()).hexdigest()

def write_recruiter():
    out = DOCS / "generated" / "recruiter" / "project-overview.mdx"
    out.parent.mkdir(parents=True, exist_ok=True)
    
    src_overview = "docs/source/overview/index.md"
    src_arch = "docs/source/architecture/system-overview.md"
    src_planes = "docs/source/architecture/content-planes.md"
    
    fm = {
        "id": "recruiter-project-overview",
        "slug": "/recruiter/project-overview",
        "title": "DOCCAD — Executive Engineering & Architecture Overview",
        "type": "generated",
        "visibility": "public",
        "audience": ["recruiter", "architect"],
        "owners": ["architecture"],
        "last_validated": "2026-09-21",
        "generated": True,
        "generation": {
            "contract": "GenerateRecruiterPage",
            "contract_version": 1,
            "prompt_version": "recruiter.v1",
            "source_documents": [
                {"id": "overview-index", "path": src_overview, "content_hash": sha256_of(src_overview)},
                {"id": "architecture-system-overview", "path": src_arch, "content_hash": sha256_of(src_arch)},
                {"id": "architecture-content-planes", "path": src_planes, "content_hash": sha256_of(src_planes)},
            ],
            "repo_evidence": ["package.json", "docusaurus.config.ts"],
            "provider": "fixture",
            "model": "deterministic-demo-fixture",
            "generation_mode": "demo",
            "generated_at": "2026-09-21T00:00:00Z",
            "approval_status": "approved-for-demo",
        }
    }
    
    body = """# Executive Engineering & Architecture Overview

<div className="alert alert--info margin-bottom--lg">
  <strong>Governance Provenance</strong>: This view was generated by contract <code>GenerateRecruiterPage v1</code> using the deterministic fixture provider. Every technical assertion below links directly to verified canonical documentation.
</div>

## 1. 30-Second Executive Summary

**DOCCAD** is an evidence-backed documentation platform built on docs-as-code principles. It decouples human-authored engineering truth (`/docs`) from audience-specific AI views (`/views`), deploying as a high-performance static website with zero runtime AI costs, latency, or single points of failure.

Key Verified Highlights:
- **Structural Plane Separation**: Two independent Docusaurus docs-plugin instances guarantee AI hallucinations cannot pollute canonical documents (<EvidenceLink to="/docs/architecture/content-planes">ADR-003</EvidenceLink>).
- **Mechanical Drift Detection**: Tracks `sha256` content digests on source files to trigger targeted, non-full-corpus regeneration (<EvidenceLink to="/docs/validation/drift-detection">Drift Detection</EvidenceLink>).
- **Offline Reliability**: 100% readable and searchable without active cloud providers (<EvidenceLink to="/docs/decisions/adr-002-docusaurus-foundation">ADR-002</EvidenceLink>).

---

## 2. Two-Minute Technical Walkthrough

Engineering teams face a dilemma: documentation is either painfully outdated or unreliably generated by opaque AI tools. DOCCAD solves this through architectural discipline:

1. **Human-Owned System of Record**: Engineers maintain canonical Markdown files and Mermaid diagrams in Git. No external CMS, vector database, or dynamic backend exists (<EvidenceLink to="/docs/decisions/adr-001-github-source-of-truth">ADR-001</EvidenceLink>).
2. **Offline AI Generation Plane**: CLI and CI pipelines invoke a thin provider abstraction to generate audience-focused views. Prompts assemble evidence strictly via Level-1 deterministic file selection (<EvidenceLink to="/docs/decisions/adr-006-retrieval-level1">ADR-006</EvidenceLink>).
3. **PR-Gated Governance**: Generated artifacts persist only through pull requests on `docs-gen/*` branches, subject to deterministic validation gates (<EvidenceLink to="/docs/decisions/adr-005-pr-gated-generation">ADR-005</EvidenceLink>).

---

## 3. Deep-Dive: Architectural Competency Mapping

| Competency Area | DOCCAD Architectural Implementation | Canonical Evidence |
|---|---|---|
| **System Security & Threat Modeling** | 6-Zone trust boundary model, strict demarcation of untrusted user input as data (`<<<EVIDENCE-DATA`), link allowlisting, and MDX script rejection. | <EvidenceLink to="/docs/security/trust-boundaries">Trust Boundaries</EvidenceLink> |
| **Privacy & Intellectual Property** | Irrevocable local provider hard-pinning for tasks marked `privacy: private`; fatal error rather than cloud fallback. | <EvidenceLink to="/docs/decisions/adr-004-provider-abstraction">ADR-004: Provider Abstraction</EvidenceLink> |
| **Deterministic Automation** | Hash-based staleness evaluation recomputes `sha256` digests, driving targeted regeneration. | <EvidenceLink to="/docs/validation/drift-detection">Drift Detection Specification</EvidenceLink> |
| **Platform Sovereignty** | Evaluated 6 documentation engines; Docusaurus 3.x selected (88.6/100) for dual-plugin separation and offline independence. | <EvidenceLink to="/docs/architecture/platform-research">Six-Platform Research</EvidenceLink> |
"""
    
    front_str = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip()
    out.write_text(f"---\n{front_str}\n---\n\n{body}\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}")


def write_interviews():
    topics = [
        ("architecture-system-overview", "docs/source/architecture/system-overview.md", "System Architecture Spine"),
        ("architecture-content-planes", "docs/source/architecture/content-planes.md", "Two Content Planes Separation"),
        ("security-trust-boundaries", "docs/source/security/trust-boundaries.md", "Security Trust Boundaries"),
        ("validation-drift-detection", "docs/source/validation/drift-detection.md", "Hash-Based Drift Detection"),
    ]
    
    out_dir = DOCS / "generated" / "interview"
    out_dir.mkdir(parents=True, exist_ok=True)
    
    for doc_id, src_path, title in topics:
        shash = sha256_of(src_path)
        
        jdata = {
            "id": doc_id,
            "elevator_pitch": f"DOCCAD implements {title} to guarantee that documentation is strictly versioned in Git, verified mechanically via hashes, and served statically without runtime AI dependencies.",
            "technical_explanation": f"In DOCCAD, {title} establishes architectural boundaries between human-authored canon and AI-generated derived views, ensuring auditability in PRs and complete offline reproducibility. Context is assembled deterministically and proven with cryptographic hashes.",
            "concepts": [
                {
                    "name": "Docs-as-code and Single Source of Truth",
                    "explanation": "Version-controlled files in Git represent the primary ground truth. No external database or CMS is permitted in the serving path."
                },
                {
                    "name": "Two-Plane Structural Separation",
                    "explanation": "Canonical documentation (/docs) and AI-generated views (/views) run in separate Docusaurus plugin instances, physically isolating human truth from bot drafts."
                },
                {
                    "name": "Mechanical Drift Detection",
                    "explanation": "Derived pages record sha256 digests of their input sources. When source bytes change, CI detects drift and schedules targeted regeneration."
                }
            ],
            "design_decisions": [
                {
                    "decision": f"Adopt {title} as an architectural invariant",
                    "rationale": "Prevents split-brain state, eliminates unverified hallucinations, and ensures predictable static builds.",
                    "evidence": doc_id
                }
            ],
            "tradeoffs": [
                {
                    "choice": "Deterministic Level-1 retrieval over embeddings",
                    "benefit": "Auditable evidence assembly with zero index infrastructure and 100% reproducible PR diffs.",
                    "cost": "Retrieval depends on frontmatter discipline and will need escalation if the corpus exceeds ~1,500 documents."
                },
                {
                    "choice": "Static-first publishing",
                    "benefit": "The site builds and serves with all AI providers down; hosting is trivial and secure.",
                    "cost": "No runtime personalization or on-demand chat — new views require a CI generation job."
                }
            ],
            "likely_questions": [
                f"What is the rationale behind {title}?",
                "How does the system prevent unreviewed AI content from entering production?",
                "Why is retrieval deterministic instead of embedding-based?"
            ],
            "example_answers": [
                {
                    "question": f"What is the rationale behind {title}?",
                    "answer": f"{title} ensures that human engineering knowledge remains the authoritative ground truth, while derived views are generated strictly via explicit task contracts and reviewed via pull requests."
                },
                {
                    "question": "How does the system prevent unreviewed AI content from entering production?",
                    "answer": "Generated views are committed to isolated docs-gen/* branches and require human peer review approval before merging into the main branch. Auto-merge is strictly disabled."
                }
            ],
            "follow_ups": [
                "How does hash-based drift detection scale as the repository grows?",
                "How the one-repair-retry policy bounds generation cost"
            ],
            "evidence_links": [
                {
                    "label": f"{title} (canonical)",
                    "to": f"/docs/{src_path.replace('docs/source/', '').replace('.md', '')}"
                }
            ],
            "generation": {
                "contract": "GenerateInterviewPrep",
                "contract_version": 1,
                "prompt_version": "interview.v1",
                "source_documents": [
                    {"id": doc_id, "path": src_path, "content_hash": shash}
                ],
                "provider": "fixture",
                "model": "deterministic-demo-fixture",
                "generation_mode": "demo",
                "generated_at": "2026-09-21T00:00:00Z",
                "approval_status": "approved-for-demo"
            }
        }
        
        jpath = out_dir / f"{doc_id}.interview.json"
        jpath.write_text(json.dumps(jdata, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {jpath.relative_to(ROOT)}")
        
        # Write MDX page
        fm = {
            "id": f"interview-{doc_id}",
            "slug": f"/interview/{doc_id}",
            "title": f"Interview Preparation — {title}",
            "type": "generated",
            "visibility": "public",
            "audience": ["interviewer", "recruiter", "developer"],
            "owners": ["architecture"],
            "last_validated": "2026-09-21",
            "generated": True,
            "generation": {
                "contract": "GenerateInterviewPrep",
                "contract_version": 1,
                "prompt_version": "interview.v1",
                "source_documents": [
                    {"id": doc_id, "path": src_path, "content_hash": shash}
                ],
                "provider": "fixture",
                "model": "deterministic-demo-fixture",
                "generation_mode": "demo",
                "generated_at": "2026-09-21T00:00:00Z",
                "approval_status": "approved-for-demo",
            }
        }
        
        mdx_content = f"""# Interview Preparation: {title}

<InterviewPrep id="{doc_id}" />
"""
        fm_str = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip()
        mpath = out_dir / f"{doc_id}.mdx"
        mpath.write_text(f"---\n{fm_str}\n---\n\n{mdx_content}\n", encoding="utf-8")
        print(f"Wrote {mpath.relative_to(ROOT)}")


def write_questions():
    q_dir = DOCS / "generated" / "questions"
    q_dir.mkdir(parents=True, exist_ok=True)
    
    questions = [
        ("q-001-canonical-separation", "Separation of Canonical and Generated Planes",
         "How does DOCCAD ensure AI-generated content does not pollute canonical documentation?",
         "docs/source/architecture/content-planes.md", "architecture-content-planes",
         "DOCCAD enforces physical separation through two independent `@docusaurus/plugin-content-docs` instances (`/docs` for human canon vs `/views` for generated views). Canonical docs are human-owned and never cite generated content, preventing hallucination loops."),
        
        ("q-002-drift-detection", "Hash-Based Drift Detection Workflow",
         "How does DOCCAD detect drift when canonical architecture or code changes?",
         "docs/source/validation/drift-detection.md", "validation-drift-detection",
         "Every derived artifact records the `sha256` content hash of its source canonical documents in frontmatter. When sources change, CI re-evaluates hashes against disk and flags only affected pages as STALE in `impact.json`, triggering targeted regeneration."),
        
        ("q-003-security-trust-zones", "Security Trust Boundaries and Untrusted Inputs",
         "What is DOCCAD's security model for prompt injection and untrusted inputs?",
         "docs/source/security/trust-boundaries.md", "security-trust-boundaries",
         "DOCCAD implements a 6-Zone Trust Model. Untrusted inputs and repository content are treated strictly as inert DATA delimited by `<<<EVIDENCE-DATA` tokens. Generated MDX is statically scanned to reject raw script tags and dynamic evaluation constructs before compilation."),
        
        ("q-004-docusaurus-selection", "Docusaurus Platform Selection Rationale",
         "Why did DOCCAD select Docusaurus over Mintlify or MkDocs?",
         "docs/source/decisions/adr-002-docusaurus-foundation.md", "decisions-adr-002-docusaurus-foundation",
         "Docusaurus 3.x won the 11-criterion weighted evaluation (88.6/100) due to native multi-instance docs separation, offline static compilation, React 19 component flexibility (`EvidenceLink`, `InterviewPrep`), and complete freedom from cloud SaaS vendor lock-in."),
        
        ("q-005-private-routing", "Private Routing and Zero Cloud Fallback",
         "How does the private routing policy prevent data leakage to cloud model providers?",
         "docs/source/decisions/adr-004-provider-abstraction.md", "decisions-adr-004-provider-abstraction",
         "Tasks marked `privacy: private` are hard-pinned to local execution (`local` provider). If the local provider is unavailable, the router terminates with a fatal `PrivacyRoutingError`, strictly prohibiting silent fallback to cloud APIs."),
        
        ("q-006-kubernetes-topology", "Kubernetes Deployment Topology (Insufficient Evidence)",
         "What is DOCCAD's multi-cluster Kubernetes deployment topology for high-frequency trading?",
         "docs/source/decisions/adr-009-deployment-github-pages.md", "decisions-adr-009-deployment-github-pages",
         "**INSUFFICIENT CANONICAL EVIDENCE**: The canonical documentation contains no evidence for Kubernetes clusters or high-frequency trading. DOCCAD is deliberately designed as a serverless static site deployed via GitHub Pages (ADR-009). The system refuses to speculate or invent unevidenced technologies.")
    ]
    
    for q_id, q_title, q_text, src_path, src_id, q_answer in questions:
        shash = sha256_of(src_path)
        fm = {
            "id": q_id,
            "slug": f"/questions/{q_id}",
            "title": f"Question: {q_title}",
            "type": "generated",
            "visibility": "public",
            "audience": ["developer", "architect"],
            "owners": ["architecture"],
            "last_validated": "2026-09-21",
            "generated": True,
            "generation": {
                "contract": "GenerateQuestionPage",
                "contract_version": 2,
                "prompt_version": "question-page.v2",
                "source_documents": [
                    {"id": src_id, "path": src_path, "content_hash": shash}
                ],
                "provider": "fixture",
                "model": "deterministic-demo-fixture",
                "generation_mode": "demo",
                "generated_at": "2026-09-21T00:00:00Z",
                "approval_status": "approved-for-demo",
            }
        }
        
        body = f"""# Question: {q_text}

## Grounded Answer

{q_answer}

## Supporting Canonical Evidence
- <EvidenceLink to="/{src_path.replace('docs/source/', 'docs/').replace('.md', '')}">Canonical Reference: {src_id}</EvidenceLink>
"""
        front_str = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip()
        qpath = q_dir / f"{q_id}.mdx"
        qpath.write_text(f"---\n{front_str}\n---\n\n{body}\n", encoding="utf-8")
        print(f"Wrote {qpath.relative_to(ROOT)}")


if __name__ == "__main__":
    write_recruiter()
    write_interviews()
    write_questions()
    print("All deterministic views seeded successfully.")
