import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the CANONICAL plane (plugin instance "source", route /docs).
const sidebars: SidebarsConfig = {
  source: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
